include_guard(GLOBAL)

set(__LIB_ROOT ${ZEPHYR_BASE}/lib)
zephyr_library_named(__utext_lib)
if (CONFIG_UT_LIB)
    message(STATUS "Include module: use zephyr/lib")
    add_subdirectory(${__LIB_ROOT} ${PACKAGES_BUILD_DIR}/lib)
else()
    if (CONFIG_UT_LIB_UTILS)
        add_subdirectory(${__LIB_ROOT}/utils ${PACKAGES_BUILD_DIR}/lib)
    else()
        zephyr_sources_ifdef(CONFIG_UT_LIB_RING_BUFFER ${__LIB_ROOT}/utils/ring_buffer.c)
    endif()
endif()
