include_guard(GLOBAL)

set(__SUBSYS_ROOT ${ZEPHYR_BASE}/subsys)
if(CONFIG_UT_SUBSYS)
    message(STATUS "Include zephyr/subsys module")
    zephyr_library_named(__utext_subsys)
    add_subdirectory(${__SUBSYS_ROOT} ${PACKAGES_BUILD_DIR}/subsys)
else()
    if (CONFIG_UT_SUBSYS_LOGGING)
        message(STATUS "Include zephyr/subsys/logging module")
        zephyr_library_named(__utext_subsys_logging)
        add_subdirectory(${__SUBSYS_ROOT}/logging ${PACKAGES_BUILD_DIR}/subsys/logging)
    endif()
endif()